# Generated by Django 3.1.9 on 2021-06-06 14:01

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('founded', models.CharField(blank=True, max_length=4)),
                ('value', models.PositiveIntegerField(verbose_name='Value compared to USD:')),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('token_or_coin', models.CharField(choices=[('Token', 'token'), ('Coin', 'coin')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['value', 'founded'],
            },
        ),
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('founded', models.CharField(blank=True, max_length=4)),
                ('value', models.PositiveIntegerField(verbose_name='Value compared to USD:')),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['value', 'founded'],
            },
        ),
    ]
